/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedChannelSyncRouteImport } from './routes/_authenticated/channel-sync'
import { Route as AuthenticatedCleanersRouteImport } from './routes/_authenticated/cleaners'
import { Route as AuthenticatedCleaningRouteImport } from './routes/_authenticated/cleaning'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedGeoTestRouteImport } from './routes/_authenticated/geo-test'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedRequestAccessRouteImport } from './routes/_authenticated/request-access'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTimeTrackingRouteImport } from './routes/_authenticated/time-tracking'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedClockTokenRouteImport } from './routes/_authenticated/clock.$token'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedSettingsImportRouteImport } from './routes/_authenticated/settings.import'
import { Route as AuthenticatedSettingsLogsRouteImport } from './routes/_authenticated/settings.logs'
import { Route as AuthenticatedPropertiesIdQrRouteImport } from './routes/_authenticated/properties.$id.qr'
import { Route as AuthenticatedPropertiesIdRoomsRouteImport } from './routes/_authenticated/properties.$id.rooms'
import { Route as ApiPublicHooksChannelOutboxRouteImport } from './routes/api/public/hooks/channel-outbox'
import { Route as ApiPublicHooksDispatchMorningRouteImport } from './routes/api/public/hooks/dispatch-morning'
import { Route as ApiPublicSyncManualRouteImport } from './routes/api/public/sync/manual'
import { Route as ApiPublicWebhooksAirbnbRouteImport } from './routes/api/public/webhooks/airbnb'
import { Route as ApiPublicWebhooksBookingRouteImport } from './routes/api/public/webhooks/booking'
import { Route as ApiPublicIcalRoomsRoomIdRouteImport } from './routes/api/public/ical/rooms/$roomId'
import { Route as ApiPublicWebhooksWubookSecretRouteImport } from './routes/api/public/webhooks/wubook/$secret'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelSyncRoute =
  AuthenticatedChannelSyncRouteImport.update({
    id: '/channel-sync',
    path: '/channel-sync',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCleanersRoute = AuthenticatedCleanersRouteImport.update({
  id: '/cleaners',
  path: '/cleaners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCleaningRoute = AuthenticatedCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeoTestRoute = AuthenticatedGeoTestRouteImport.update({
  id: '/geo-test',
  path: '/geo-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestAccessRoute =
  AuthenticatedRequestAccessRouteImport.update({
    id: '/request-access',
    path: '/request-access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeTrackingRoute =
  AuthenticatedTimeTrackingRouteImport.update({
    id: '/time-tracking',
    path: '/time-tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClockTokenRoute = AuthenticatedClockTokenRouteImport.update({
  id: '/clock/$token',
  path: '/clock/$token',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsImportRoute =
  AuthenticatedSettingsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLogsRoute =
  AuthenticatedSettingsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPropertiesIdQrRoute =
  AuthenticatedPropertiesIdQrRouteImport.update({
    id: '/properties/$id/qr',
    path: '/properties/$id/qr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIdRoomsRoute =
  AuthenticatedPropertiesIdRoomsRouteImport.update({
    id: '/properties/$id/rooms',
    path: '/properties/$id/rooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksChannelOutboxRoute =
  ApiPublicHooksChannelOutboxRouteImport.update({
    id: '/api/public/hooks/channel-outbox',
    path: '/api/public/hooks/channel-outbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchMorningRoute =
  ApiPublicHooksDispatchMorningRouteImport.update({
    id: '/api/public/hooks/dispatch-morning',
    path: '/api/public/hooks/dispatch-morning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncManualRoute = ApiPublicSyncManualRouteImport.update({
  id: '/api/public/sync/manual',
  path: '/api/public/sync/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksAirbnbRoute = ApiPublicWebhooksAirbnbRouteImport.update({
  id: '/api/public/webhooks/airbnb',
  path: '/api/public/webhooks/airbnb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBookingRoute =
  ApiPublicWebhooksBookingRouteImport.update({
    id: '/api/public/webhooks/booking',
    path: '/api/public/webhooks/booking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIcalRoomsRoomIdRoute =
  ApiPublicIcalRoomsRoomIdRouteImport.update({
    id: '/api/public/ical/rooms/$roomId',
    path: '/api/public/ical/rooms/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksWubookSecretRoute =
  ApiPublicWebhooksWubookSecretRouteImport.update({
    id: '/api/public/webhooks/wubook/$secret',
    path: '/api/public/webhooks/wubook/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/channel-sync': typeof AuthenticatedChannelSyncRoute
  '/cleaners': typeof AuthenticatedCleanersRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/geo-test': typeof AuthenticatedGeoTestRoute
  '/me': typeof AuthenticatedMeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/request-access': typeof AuthenticatedRequestAccessRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/time-tracking': typeof AuthenticatedTimeTrackingRoute
  '/api/chat': typeof ApiChatRoute
  '/clock/$token': typeof AuthenticatedClockTokenRoute
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/properties/$id/qr': typeof AuthenticatedPropertiesIdQrRoute
  '/properties/$id/rooms': typeof AuthenticatedPropertiesIdRoomsRoute
  '/api/public/hooks/channel-outbox': typeof ApiPublicHooksChannelOutboxRoute
  '/api/public/hooks/dispatch-morning': typeof ApiPublicHooksDispatchMorningRoute
  '/api/public/sync/manual': typeof ApiPublicSyncManualRoute
  '/api/public/webhooks/airbnb': typeof ApiPublicWebhooksAirbnbRoute
  '/api/public/webhooks/booking': typeof ApiPublicWebhooksBookingRoute
  '/api/public/ical/rooms/$roomId': typeof ApiPublicIcalRoomsRoomIdRoute
  '/api/public/webhooks/wubook/$secret': typeof ApiPublicWebhooksWubookSecretRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/channel-sync': typeof AuthenticatedChannelSyncRoute
  '/cleaners': typeof AuthenticatedCleanersRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/geo-test': typeof AuthenticatedGeoTestRoute
  '/me': typeof AuthenticatedMeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/request-access': typeof AuthenticatedRequestAccessRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/time-tracking': typeof AuthenticatedTimeTrackingRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/clock/$token': typeof AuthenticatedClockTokenRoute
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/properties/$id/qr': typeof AuthenticatedPropertiesIdQrRoute
  '/properties/$id/rooms': typeof AuthenticatedPropertiesIdRoomsRoute
  '/api/public/hooks/channel-outbox': typeof ApiPublicHooksChannelOutboxRoute
  '/api/public/hooks/dispatch-morning': typeof ApiPublicHooksDispatchMorningRoute
  '/api/public/sync/manual': typeof ApiPublicSyncManualRoute
  '/api/public/webhooks/airbnb': typeof ApiPublicWebhooksAirbnbRoute
  '/api/public/webhooks/booking': typeof ApiPublicWebhooksBookingRoute
  '/api/public/ical/rooms/$roomId': typeof ApiPublicIcalRoomsRoomIdRoute
  '/api/public/webhooks/wubook/$secret': typeof ApiPublicWebhooksWubookSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/channel-sync': typeof AuthenticatedChannelSyncRoute
  '/_authenticated/cleaners': typeof AuthenticatedCleanersRoute
  '/_authenticated/cleaning': typeof AuthenticatedCleaningRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRoute
  '/_authenticated/geo-test': typeof AuthenticatedGeoTestRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/request-access': typeof AuthenticatedRequestAccessRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/time-tracking': typeof AuthenticatedTimeTrackingRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clock/$token': typeof AuthenticatedClockTokenRoute
  '/_authenticated/settings/import': typeof AuthenticatedSettingsImportRoute
  '/_authenticated/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/properties/$id/qr': typeof AuthenticatedPropertiesIdQrRoute
  '/_authenticated/properties/$id/rooms': typeof AuthenticatedPropertiesIdRoomsRoute
  '/api/public/hooks/channel-outbox': typeof ApiPublicHooksChannelOutboxRoute
  '/api/public/hooks/dispatch-morning': typeof ApiPublicHooksDispatchMorningRoute
  '/api/public/sync/manual': typeof ApiPublicSyncManualRoute
  '/api/public/webhooks/airbnb': typeof ApiPublicWebhooksAirbnbRoute
  '/api/public/webhooks/booking': typeof ApiPublicWebhooksBookingRoute
  '/api/public/ical/rooms/$roomId': typeof ApiPublicIcalRoomsRoomIdRoute
  '/api/public/webhooks/wubook/$secret': typeof ApiPublicWebhooksWubookSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai'
    | '/analytics'
    | '/calendar'
    | '/channel-sync'
    | '/cleaners'
    | '/cleaning'
    | '/dispatch'
    | '/geo-test'
    | '/me'
    | '/notifications'
    | '/request-access'
    | '/reservations'
    | '/rooms'
    | '/settings'
    | '/team'
    | '/time-tracking'
    | '/api/chat'
    | '/clock/$token'
    | '/settings/import'
    | '/settings/logs'
    | '/properties/'
    | '/properties/$id/qr'
    | '/properties/$id/rooms'
    | '/api/public/hooks/channel-outbox'
    | '/api/public/hooks/dispatch-morning'
    | '/api/public/sync/manual'
    | '/api/public/webhooks/airbnb'
    | '/api/public/webhooks/booking'
    | '/api/public/ical/rooms/$roomId'
    | '/api/public/webhooks/wubook/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/ai'
    | '/analytics'
    | '/calendar'
    | '/channel-sync'
    | '/cleaners'
    | '/cleaning'
    | '/dispatch'
    | '/geo-test'
    | '/me'
    | '/notifications'
    | '/request-access'
    | '/reservations'
    | '/rooms'
    | '/settings'
    | '/team'
    | '/time-tracking'
    | '/api/chat'
    | '/'
    | '/clock/$token'
    | '/settings/import'
    | '/settings/logs'
    | '/properties'
    | '/properties/$id/qr'
    | '/properties/$id/rooms'
    | '/api/public/hooks/channel-outbox'
    | '/api/public/hooks/dispatch-morning'
    | '/api/public/sync/manual'
    | '/api/public/webhooks/airbnb'
    | '/api/public/webhooks/booking'
    | '/api/public/ical/rooms/$roomId'
    | '/api/public/webhooks/wubook/$secret'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ai'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/channel-sync'
    | '/_authenticated/cleaners'
    | '/_authenticated/cleaning'
    | '/_authenticated/dispatch'
    | '/_authenticated/geo-test'
    | '/_authenticated/me'
    | '/_authenticated/notifications'
    | '/_authenticated/request-access'
    | '/_authenticated/reservations'
    | '/_authenticated/rooms'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/time-tracking'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/clock/$token'
    | '/_authenticated/settings/import'
    | '/_authenticated/settings/logs'
    | '/_authenticated/properties/'
    | '/_authenticated/properties/$id/qr'
    | '/_authenticated/properties/$id/rooms'
    | '/api/public/hooks/channel-outbox'
    | '/api/public/hooks/dispatch-morning'
    | '/api/public/sync/manual'
    | '/api/public/webhooks/airbnb'
    | '/api/public/webhooks/booking'
    | '/api/public/ical/rooms/$roomId'
    | '/api/public/webhooks/wubook/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksChannelOutboxRoute: typeof ApiPublicHooksChannelOutboxRoute
  ApiPublicHooksDispatchMorningRoute: typeof ApiPublicHooksDispatchMorningRoute
  ApiPublicSyncManualRoute: typeof ApiPublicSyncManualRoute
  ApiPublicWebhooksAirbnbRoute: typeof ApiPublicWebhooksAirbnbRoute
  ApiPublicWebhooksBookingRoute: typeof ApiPublicWebhooksBookingRoute
  ApiPublicIcalRoomsRoomIdRoute: typeof ApiPublicIcalRoomsRoomIdRoute
  ApiPublicWebhooksWubookSecretRoute: typeof ApiPublicWebhooksWubookSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel-sync': {
      id: '/_authenticated/channel-sync'
      path: '/channel-sync'
      fullPath: '/channel-sync'
      preLoaderRoute: typeof AuthenticatedChannelSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleaners': {
      id: '/_authenticated/cleaners'
      path: '/cleaners'
      fullPath: '/cleaners'
      preLoaderRoute: typeof AuthenticatedCleanersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleaning': {
      id: '/_authenticated/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof AuthenticatedCleaningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/geo-test': {
      id: '/_authenticated/geo-test'
      path: '/geo-test'
      fullPath: '/geo-test'
      preLoaderRoute: typeof AuthenticatedGeoTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/request-access': {
      id: '/_authenticated/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof AuthenticatedRequestAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time-tracking': {
      id: '/_authenticated/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof AuthenticatedTimeTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clock/$token': {
      id: '/_authenticated/clock/$token'
      path: '/clock/$token'
      fullPath: '/clock/$token'
      preLoaderRoute: typeof AuthenticatedClockTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/import': {
      id: '/_authenticated/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AuthenticatedSettingsImportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/logs': {
      id: '/_authenticated/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AuthenticatedSettingsLogsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/properties/$id/qr': {
      id: '/_authenticated/properties/$id/qr'
      path: '/properties/$id/qr'
      fullPath: '/properties/$id/qr'
      preLoaderRoute: typeof AuthenticatedPropertiesIdQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$id/rooms': {
      id: '/_authenticated/properties/$id/rooms'
      path: '/properties/$id/rooms'
      fullPath: '/properties/$id/rooms'
      preLoaderRoute: typeof AuthenticatedPropertiesIdRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/channel-outbox': {
      id: '/api/public/hooks/channel-outbox'
      path: '/api/public/hooks/channel-outbox'
      fullPath: '/api/public/hooks/channel-outbox'
      preLoaderRoute: typeof ApiPublicHooksChannelOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-morning': {
      id: '/api/public/hooks/dispatch-morning'
      path: '/api/public/hooks/dispatch-morning'
      fullPath: '/api/public/hooks/dispatch-morning'
      preLoaderRoute: typeof ApiPublicHooksDispatchMorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/manual': {
      id: '/api/public/sync/manual'
      path: '/api/public/sync/manual'
      fullPath: '/api/public/sync/manual'
      preLoaderRoute: typeof ApiPublicSyncManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/airbnb': {
      id: '/api/public/webhooks/airbnb'
      path: '/api/public/webhooks/airbnb'
      fullPath: '/api/public/webhooks/airbnb'
      preLoaderRoute: typeof ApiPublicWebhooksAirbnbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/booking': {
      id: '/api/public/webhooks/booking'
      path: '/api/public/webhooks/booking'
      fullPath: '/api/public/webhooks/booking'
      preLoaderRoute: typeof ApiPublicWebhooksBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ical/rooms/$roomId': {
      id: '/api/public/ical/rooms/$roomId'
      path: '/api/public/ical/rooms/$roomId'
      fullPath: '/api/public/ical/rooms/$roomId'
      preLoaderRoute: typeof ApiPublicIcalRoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/wubook/$secret': {
      id: '/api/public/webhooks/wubook/$secret'
      path: '/api/public/webhooks/wubook/$secret'
      fullPath: '/api/public/webhooks/wubook/$secret'
      preLoaderRoute: typeof ApiPublicWebhooksWubookSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsImportRoute: typeof AuthenticatedSettingsImportRoute
  AuthenticatedSettingsLogsRoute: typeof AuthenticatedSettingsLogsRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsImportRoute: AuthenticatedSettingsImportRoute,
  AuthenticatedSettingsLogsRoute: AuthenticatedSettingsLogsRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChannelSyncRoute: typeof AuthenticatedChannelSyncRoute
  AuthenticatedCleanersRoute: typeof AuthenticatedCleanersRoute
  AuthenticatedCleaningRoute: typeof AuthenticatedCleaningRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRoute
  AuthenticatedGeoTestRoute: typeof AuthenticatedGeoTestRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRequestAccessRoute: typeof AuthenticatedRequestAccessRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTimeTrackingRoute: typeof AuthenticatedTimeTrackingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClockTokenRoute: typeof AuthenticatedClockTokenRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedPropertiesIdQrRoute: typeof AuthenticatedPropertiesIdQrRoute
  AuthenticatedPropertiesIdRoomsRoute: typeof AuthenticatedPropertiesIdRoomsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChannelSyncRoute: AuthenticatedChannelSyncRoute,
  AuthenticatedCleanersRoute: AuthenticatedCleanersRoute,
  AuthenticatedCleaningRoute: AuthenticatedCleaningRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRoute,
  AuthenticatedGeoTestRoute: AuthenticatedGeoTestRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRequestAccessRoute: AuthenticatedRequestAccessRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTimeTrackingRoute: AuthenticatedTimeTrackingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClockTokenRoute: AuthenticatedClockTokenRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedPropertiesIdQrRoute: AuthenticatedPropertiesIdQrRoute,
  AuthenticatedPropertiesIdRoomsRoute: AuthenticatedPropertiesIdRoomsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksChannelOutboxRoute: ApiPublicHooksChannelOutboxRoute,
  ApiPublicHooksDispatchMorningRoute: ApiPublicHooksDispatchMorningRoute,
  ApiPublicSyncManualRoute: ApiPublicSyncManualRoute,
  ApiPublicWebhooksAirbnbRoute: ApiPublicWebhooksAirbnbRoute,
  ApiPublicWebhooksBookingRoute: ApiPublicWebhooksBookingRoute,
  ApiPublicIcalRoomsRoomIdRoute: ApiPublicIcalRoomsRoomIdRoute,
  ApiPublicWebhooksWubookSecretRoute: ApiPublicWebhooksWubookSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
